name: test
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          repository: 'reiked/helm-operator-get-started'
          token: '${{ secrets.DEPLOYMENT_USER_TOKEN }}'
      - name: List Files
        run: |
          echo "test" >> test.text
      - name: commit
        run: |
          git add .
          git commit -m "generated"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_USER_TOKEN }}